image: docker:20

stages:
  - build

docker_build:
  stage: build
  before_script:
    - docker login -u $DOCKER_REGISTRY_USER -p $DOCKER_REGISTRY_PASSWORD
  script:
    - docker build -t jopouradier/fireapp:latest .
    - docker push jopouradier/fireapp:latest .