stages:
  - build

docker_build:
  image: docker:19.03.12
  stage: build
  services:
    - docker:19.03.12-dind
  before_script:
    - docker login -u $DOCKER_REGISTRY_PASSWORD -p $DOCKER_REGISTRY_PASSWORD registry.gitlab.com
  script:
    - docker build -t registry.gitlab.com/cpelyon/4eti-2022-2023/projet_clbd_g4_2022-2023:latest .
    - docker push registry.gitlab.com/cpelyon/4eti-2022-2023/projet_clbd_g4_2022-2023